sub main()
    print "BrighterTube initialized successfully."
    
    ' The screen is typically created by the SceneGraph framework automatically 
    ' via MainScene.xml, but you can initialize global data contexts here if needed.
    
    screen = CreateObject("roSGScreen")
    m.port = CreateObject("roMessagePort")
    screen.setMessagePort(m.port)
    
    scene = screen.CreateScene("MainScene")
    screen.Show()
    
    while true
        msg = wait(0, m.port)
        msgType = type(msg)
        if msgType = "roSGScreenEvent"
            if msg.IsScreenClosed() then return
        end if
    end while
end sub
